version: 2

models:
  - name: dim_games
    columns:
      - name: app_id
        description: Native game ID on Steam
      - name: title
        description: Game title
      - name: date_release
        description: Game release date
      - name: support_win
        description: If the game supports Windows?
      - name: support_mac
        description: If the game supports MacOS?
      - name: support_linux
        description: If the game supports Linux?
      - name: steam_deck
        description: Has support on the Steam Deck?
      - name: price_final
        description: Price in US dollars $ calculated after the discount
      - name: price_original
        description: Price in US dollars $ before the discount
      - name: discount_ratio
        description: Discount percentage
      - name: is_discount
        description: If the game is discount?
      - name: rating_category
        description: Game rating category, including ["Negative", "Very Negative", "Overwhelmingly Negative", "Mostly Negative", "Mixed", "Mostly Positive", "Very Positive", "Positive", "Overwhelmingly Positive"]
      - name: positive_ratio
        description: Ratio of positive feedbacks
      - name: user_reviews
        description: Amount of user reviews availble on the Steam page (NOT in the dataset)
      - name: app_description
        description: Description of the game
      - name: app_tags
        description: Tags (genres) on the game

  - name: dim_tags
    columns:
      - name: app_id
        description: Native game ID on Steam
        tests:
          - relationships:
              to: ref('dim_games')
              field: app_id
      - name: tag
        description: Tag (genre) on the game

  - name: dim_users
    columns:
      - name: user_id
        description: User's auto-generated ID
      - name: num_of_games
        description: Number of games/add-ons purchased by the user
      - name: reviews
        description: Number of reviews published

  - name: fct_recommendations
    columns: 
      - name: user_id
        description: User's auto-generated ID
        tests:
          - relationships:
              to: ref('dim_users')
              field: user_id
      - name: app_id
        description: Native game ID on Steam
        tests:
          - relationships:
              to: ref('dim_games')
              field: app_id
      - name: review_id
        description: Autogenerated review ID
      - name: review_date
        description: Date of review publishing 
      - name: is_recommended
        description: Is the user recommending the game?
      - name: hours
        description: How may hours played by user
      - name: type_of_player
        description: If the player spends lots of time on the game, including ["dedicated", "occasional"]
      - name: num_of_helpful
        description: How many users found a recommendation helpful
      - name: num_of_funny
        description: How many users found a recommendation funny